[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[log]
  level = "DEBUG"
  format = "json"

[accessLog]
  format = "json"
[api]

[ping]

[providers.kubernetesCRD]