apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: apiserver
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`*`)
    services:
    - name: apiserver
      port: 6443