apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  containers:
    - name: test
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: nginx
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 8899
      targetPort: 80
  type: NodePort