apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: test
  labels:
    app: client
spec:
  replicas: 1
  template:
    metadata:
      name: client
      labels:
        app: client
    spec:
      serviceAccountName: admin
      containers:
        - name: client
          image: ccr.ccs.tencentyun.com/k8s-test/test:init-v1
          imagePullPolicy: IfNotPresent
          command:
            - sleep
            - "10000"
          volumeMounts:
            - mountPath: /pki/ca
              name: ca-pki
              readOnly: true
            - mountPath: /pki/etcd
              name: etcd-pki
              readOnly: true
            - mountPath: /pki/server
              name: k8s-server
              readOnly: true
            - mountPath: /pki/client
              name: k8s-client
              readOnly: true
            - mountPath: /home/node/
              name: nodeconfig
              readOnly: true
            - mountPath: /home/admin
              name: adminconfig
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: ca-pki
          secret:
            secretName: ca-pki
        - name: etcd-pki
          secret:
            secretName: etcd-pki
        - name: k8s-server
          secret:
            secretName: k8s-server
        - name: k8s-client
          secret:
            secretName: k8s-client
        - name: nodeconfig
          secret:
            secretName: nodeconfig
        - name: adminconfig
          secret:
            secretName: config
  selector:
    matchLabels:
      app: client