apiVersion: batch/v1
kind: Job
metadata:
  name: postinstall
  namespace: test
  labels:
    app: postinstall
spec:
  template:
    metadata:
      name: postinstall
      labels:
        app: postinstall
    spec:
      serviceAccountName: admin
      containers:
        - name: postinstall
          image: ccr.ccs.tencentyun.com/k8s-test/test:init-v1
          imagePullPolicy: IfNotPresent
          command:
            - kubectl
            - --kubeconfig=admin/admin.config
            - create
            - clusterrolebinding
            - cluster-node
            - --clusterrole=system:node
            - --user=kubernetes-node
            - --group=system:node
          volumeMounts:
            - mountPath: /pki/ca
              name: ca-pki
              readOnly: true
            - mountPath: /pki/etcd
              name: etcd-pki
              readOnly: true
            - mountPath: /pki/server
              name: k8s-server
              readOnly: true
            - mountPath: /pki/client
              name: k8s-client
              readOnly: true
            - mountPath: /home/node/
              name: nodeconfig
              readOnly: true
            - mountPath: /home/admin
              name: adminconfig
              readOnly: true
      volumes:
        - name: ca-pki
          secret:
            secretName: ca-pki
        - name: etcd-pki
          secret:
            secretName: etcd-pki
        - name: k8s-server
          secret:
            secretName: k8s-server
        - name: k8s-client
          secret:
            secretName: k8s-client
        - name: nodeconfig
          secret:
            secretName: nodeconfig
        - name: adminconfig
          secret:
            secretName: config
      restartPolicy: Never