apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init
  namespace: test
  labels:
    app: init
spec:
  template:
    metadata:
      name: init
      labels:
        app: init
    spec:
      serviceAccountName: admin
      containers:
        - name: init
          image: ccr.ccs.tencentyun.com/k8s-test/test:init-v1
          command:
            - sh 
            - /home/init.sh
          env:
            - name: APISERVER_ADDRESS
              value: 'apiserver'
            - name: FRONT_APISERVER_ADDRESS
              value: '42.193.139.71'
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: test